name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: build release
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: make CONF=Release
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Package
        run: |
          mkdir -p escript
          cp -R dist escript/
          cp -R samples escript/
          tar -czvf escript-${{ steps.get_version.outputs.VERSION }}.tar.gz escript
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: escript-${{ steps.get_version.outputs.VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
